name: Update Submodules

on:
  push:
    paths:
      - "frontend-repo/**"
      - "backend-repo/**"

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Update Submodules
        run: |
          git submodule update --remote
          git add .
          git commit -m "Update submodules"
          git push origin master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
