name: Sync Repos

on:
  push:
    branches:
      - main

jobs:
  sync-repos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout fullstack-repo
        uses: actions/checkout@v2
        with:
          repository: MohammadOsseily/fullstack-repo
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: fullstack-repo

      - name: Checkout frontend-repo
        uses: actions/checkout@v2
        with:
          repository: MohammadOsseily/frontend-repo
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: fullstack-repo/frontend-repo

      - name: Checkout backend-repo
        uses: actions/checkout@v2
        with:
          repository: MohammadOsseily/backend-repo
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: fullstack-repo/backend-repo

      - name: Sync frontend-repo to fullstack-repo
        run: |
          rsync -av --exclude='.git' fullstack-repo/frontend-repo/ fullstack-repo/frontend-repo/
          cd fullstack-repo
          git add frontend-repo
          git commit -m "Update frontend-repo" || echo "No changes to commit"
          git push origin main

      - name: Sync backend-repo to fullstack-repo
        run: |
          rsync -av --exclude='.git' fullstack-repo/backend-repo/ fullstack-repo/backend-repo/
          cd fullstack-repo
          git add backend-repo
          git commit -m "Update backend-repo" || echo "No changes to commit"
          git push origin main
